# Generated by Django 5.2.3 on 2025-07-02 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aastha', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='treatments/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='aastha.treatmentcategory')),
            ],
        ),
    ]
